### ISSUE TITLE
rename op list

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#2120]
## rename

- [ ] output to audiooutput
- [ ] microphone to audioinput
- [x] deprecated MouseCursorImage_v2 - use cursor v2 op
- [x] deprecate smoothstep/smootherstep  #7563
- [x] switchshader should be deprecated
- [x] objecttrigger triggerobject
- [x] hyperlink into openUrlWindow
- [ ] deprecate touchscreen
- [x] crossfade op into anim namespace
- [x] Ops.Deprecated.Admin.ShadowModule into Ops.Extension.Deprecated.ShadowModule (or delete this last .Admin. op?)
- [x] transform into Ops.Graphics
- [x] transformView into Ops.Graphics
- [x] orbitcontrols into Ops.Graphics
- [x] meshes into Ops.Graphics 
- [x] deprecate elementPointerEvents 
- [x] deprecate Ops.Html.ElementInteraction
- [x] namespace for html elements, that create elements
- [x] rename ElementCssFont to ElementCssText
- [x] deprecate Array3FlipAxis - does not work, does not flip axis, can be done with reverse/swizzle
- [x] deprecate ArraySetArray - use  comparray
- [x] deprecate HSBtoRGB
- [x] deprecate cannonjs
- [x] create ops.html.css
- [x] deprecate exitError op
- [x] deprecate Ops.Gl.Matrix.RandomGridPlacement
- [x] undeprecate parametric surface op
- [x] TextureToPoints -> TextureToRandomPoints
- [x] TextureToColorArray -> TextureToArray
- [x] remaining Ops.Deprecated to extension
- [x] touchscreen - when pointer op is ready
- [x] ArrayChangedTrigger - deprecate, use TriggerOnChangeArray

---
## old

- [x] all array3 ops in Ops.Array into Ops.Array.PointArray
- [x] deprecate: Ops.Json.GetStringFromObject (use ObjectGetString)
- [x] deprecate: Ops.Gl.Matrix.ArrayTranslate
- [x] deprecate: Ops.Gl.WebGlVersion - use glInfo
- [x] deprecate: Ops.Debug.Trace
- [x] deprecate: Ops.Gl.LetterBox
- [x] deprecate: Ops.Html.RemoveAllClasses
- [x] deprecate: Ops.Trigger.IfEqualsThen   
- [x] deprecate: Ops.Array.SortArrayObjectsByKey
- [x] deprecate vizstring / rename vizstringlong to vizString
- [x] parsefloat - stringToNumber
- [x] deprecate Subpatch2Temp
- [x] remove temp ? Ops.Ui.Subpatch2Temp
- [x] rename extension recklesshtml
- [x] rename Ops.Number.ToggleNumber - boolToNumber_v2
- [x] deprecate Ops.Boolean.ToggleBoolValue - use not
- [x] deprecate Ops.Gl.Meshes.ParametricSurface
- [x] ops.json byPath to ops.data.jsonPath.* - update defaultops.js !!
- [x] circularpoints replace pointsCircle ?
- [x] deprecate loadingStatusTak
- [x] arraysmooth vs smootharray
- [x] deprectae Array1To3 -
- [x] iteratorArray3 to array3Iterator
- [x] move base64 stuff to Ops.String.Base64
- [x] deprecate scaleXYZ
- [x] deprecate old supershape op
- [x] deprecate  Ops.Html.ElementSize - use: elementClientRect
- [x] deprecate Ops.Gl.Shader.PositionAsColorMaterial - use: Ops.Gl.Shader.AttributeAsColorMaterial
- [x] rename Ops.Graphics.Intersection.IntersectRaycast to Ops.Graphics.Intersection.IntersectTestRaycast
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveArray to SocketClusterReceiveArray
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveBoolean to SocketClusterReceiveBoolean
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveNumber to SocketClusterReceiveNumber 
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveObject to SocketClusterReceiveObject 
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveString to SocketClusterReceiveString 
- [x] rename Ops.Extension.SocketCluster.SocketClusterRecieveTrigger to SocketClusterReceiveTrigger
- [x] rename matcapmaterialNew - remove New
- [x] rename Texture2ColorArray to TextureToColorArray
- [x] rename canvas2texture - canvasToTexture

---

- [x] rename  Ops.Html.EventListener to Ops.Html.Event.ElementPointerEvents
- [x] rename Ops.Html.Event.CustomEventListener to Ops.Html.Event.ElementEventListener
- [x] deprecate localtexturefile
- [x] ObjectValues -> ObjectValuesAsArray
- [x] deprecate switchstringboolean -> boolToString
- [x] deprecate Ops.Number.NumberSwitchBoolean -> BoolToNumber
- [x] comp ops: into compose.object / compose.string / compose.array
- [x] particle spray -> array/points
- [x] lsystem -> extension
- [x] remove Ops.Game
- [x] browser ns ->devices
- [x] webxr -> devices
- [x] Ops.Arrays vs Ops.Array
- [x] ops.devices vs ops.device.
- [x] textureEffects/Imagecompose 
- [x] why do we habe ops.array AND ops.arrays
- [x] ops.value NS should be removed
- [x] valuechangedtrigger rename to numberchangedtrigger
- [x] milliseconds -> date
- [x] timesinceTrigger->trigger ns
- [x] delayedtrigger->trigger ns
- [x] ops.points -> Ops.Array.PointArray

---

- [x] move to graphics namespace: Ops.Gl.DepthTest
- [x] move to graphics namespace: Ops.Gl.FaceCulling_v2
- [x] ajaxRequest to httpRequest
- [x] deprecate Ops.Array.ArraySetObject
- [x] deprecate Ops.Array.ArraySetString
- [x] deprecate Ops.Array.ArraySetNumber3
- [x] deprecate Ops.Gl.AspectRatio

--- 

- [x] deprecate Ops.Gl.TextureEffects.SSAO_v2
- [x] deprecate customop
- [x] render2texture renderToTexture
- [x] triggerBool to boolByTrigger
- [x] setNumberOnTrigger to TriggerNumber
- [x] triggerNumber to numberByTrigger
- [x] move ammo to extension: tell that its unsupported
- [x]  deprecate viewport2
- [ ]  add more stuff to Ops.Data
- [x] Ops.Gl.Geometry ops to ops.graphics.geometry...

--- 
- [x] deprecate sampleplayer
- [x] pickingmaterial
- [ ] interactive rectangle
- [x] Ops.Values.FreezeArray to Ops.ArraysFreezeArray
- [x] Ops.Values.FreezeNumber to Ops.Value.FreezeNumber
- [x] Ops.Values.SequenceNumbers to Ops.Value.SequenceNumbers
- [x] Ops.Values.SequenceStrings to Ops.String.SequenceStrings
- [x] Ops.Values.FreezeString to Ops.String.FreezeString
- [x] Ops.Values.SequenceObjects to Ops.Json.SequenceObjects
- [x] deprecate soundcloud
- [x] ?make extension fxhash
- [x] ?make extension Ops.WebAudio.TextToSpeech
- [x] ?make extension Ops.Libs.Trackingjs
- [x] ?make extension lottie
- [x] ?make extension mediapipe
- [x] ?make extension opentype
- [x] Ops.Gl.TextureEffects.ColorMapRange to Ops.Gl.TextureEffects.Math.ColorMapRange
- [x] Ops.Gl.TextureEffect.RgbeToFloat32Texture to Ops.Gl.Math.TextureEffects.RgbeToFloat32Texture
- [x] Ops.Gl.Meshes.TriangleArray_v2 - to: Ops.Graphics.Geometry.TriangleArrayToGeometry
- [x] Ops.Gl.TesselateGeometry - to: Ops.Graphics.Geometry.TesselateGeometry
- [x] Ops.Gl.Geometry.AlignGeometry - to: Ops.Graphics.Geometry.AlignGeometry
- [x] Ops.Gl.Geometry.DivideGeometry - to: Ops.Graphics.Geometry.DivideGeometry
- [x] Ops.Gl.Geometry.GeometryInfo - to: Ops.Graphics.Geometry.GeometryInfo
- [x] Ops.Gl.Geometry.GeometryExtrude - to: Ops.Graphics.Geometry.GeometryExtrude
- [x] Ops.Gl.Geometry.FreezeMeshes - to: Ops.Graphics.Geometry.FreezeMeshes
- [x] Ops.Gl.Geometry.GeometryMerge - to: Ops.Graphics.Geometry.GeometryMerge
- [x] Ops.Gl.Geometry.GeometryPoints - to: Ops.Graphics.Geometry.GeometryAttributes
- [x] Ops.Gl.Geometry.GeometryToObj - to: Ops.Graphics.Geometry.GeometryToObj
- [x] Ops.Gl.Geometry.SortGeometryAxis - to: Ops.Graphics.Geometry.SortGeometryAxis
- [x] Ops.Gl.Geometry.ScaleGeometry - to: Ops.Graphics.Geometry.ScaleGeometry
- [x] Ops.Gl.Geometry.ReverseVertices - to: Ops.Graphics.Geometry.ReverseVertices
- [x] Ops.Gl.Geometry.GeometryUnIndex - to: Ops.Graphics.Geometry.GeometryUnIndex
- [x] Ops.Gl.Geometry.SvgPathToGeometry_v2 - to: Ops.Graphics.Geometry.SvgPathToGeometry_v2
- [x] Ops.Gl.Geometry.TransformGeometry - to: Ops.Graphics.Geometry.TransformGeometry
- [ ] Ops.Dev.Gl.Geometry.CopyGeometry - to: Ops.Graphics.Geometry.CopyGeometry
- [x] Ops.Gl.RandomizeTriangles - to: Ops.Graphics.Geometry.RandomizeTriangles
- [x] Ops.Geometry.BoundingBox - to: Ops.Graphics.Geometry.BoundingBox
- [x] Ops.Geometry.CalculateNormals - to: Ops.Graphics.Geometry.CalculateNormals
- [x] Ops.Geometry.GeometryToWireframeArray3 - to: Ops.Graphics.Geometry.GeometryToWireframeArray3
- [x] Ops.Geometry.Triangulate2dPath - to: Ops.Graphics.Geometry.Triangulate2dPath
- [x] TextureFromColorArray to  ArrayToTexture
- [x] rename Ops.Array.RandomArrays to Ops.Array.RandomNumbersArray_v4
- [x] deprecate Ops.Array.RandomNumbersArray3 (v1 and v2)
- [x] deprecate Ops.Array.RandomNumbersArray4 (v1 and v2)
- [x] deprecate objectiterate
- [x] fix typo in getProjectonMatrix
- [ ] TextureFromColorArray -> ArrayToTexture
- [x] rename Ops.Array.ParseArray_v2 to Ops.Array.StringToArray
- [x] Ops.Sequence to Ops.Trigger.Sequence

-------------------------

- [x] deprecate Ops.String.Split_v2
- [ ] rename Ops.Gl.TextureEffects.TexMathModulo to Ops.Gl.TextureEffects.Math.RgbModulo
- [x] rename Ops.Gl.TextureEffects.RGBMath to Ops.Gl.TextureEffects.Math.RgbMath
- [x] rename existing  diffusereaction op to v1 in new extension namespace...
- [x] deprecate Ops.Gl.Matrix.CircleTransform - use circlularpoints
- [ ] deprecate Ops.Math.CircleCoordinates - use circlularpoints
- [ ] deprecate Ops.Gl.Shader.ChromaKeyMaterial (use: texeffect)
- [x] deprecate Ops.Gl.Array3ToTexture (use: texturefromcolorarray)
- [x] deprecate Ops.WebAudio.Scale
- [x] deprecate mqtt
- [ ] deprecate LambertMatetial
- [x] Ops.Gl.Shader.ShowNormalsMaterial to AttributeAsColorMaterial (?)
- [x] deprecate showTexcoordmaterial from now on use AttributeAsColorMaterial
- [x] Ops.Gl.Textures.Float32ToRgbeTexture to Ops.Gl.TextureEffects.Float32ToRgbeTexture 
- [x] Ops.Mesh.Triangulate2dPath to Ops.Gl.Geometries
- [x] deprecate Ops.Api.Ifttt.IftttTrigger
- [x] deprecate Ops.Gl.ShaderEffects.Bulge
- [x] deprecate Ops.Gl.MorphGeometries - use meshmorph...
- [x] Ops.Gl.TextureEffects.PaletteTexture not a textureeffect, more texgen
- [x] deprecate cannon
- [x] Ops.Gl.CalculateNormals move to geometry namespae
- [x] deprecate Ops.Api.ThingSpeak
- [x] deprecate Ops.Gl.Shader.TextureLookupColorMaterial
- [x] deprecate Ops.InteractionListener
- [x] deprecate Ops.Json.ObjectRelay
- [x] deprecate Ops.String.HashIdEncode
- [x] deprecate Ops.String.HashIdDecode
- [ ] deprecate   Ops.Gl.SaveScreenShot_v3  ?
- [x] deprecate Ops.Json.ObjectRelay
- [x] deprecate cannon ?
- [x] deprecate OpsObjectChanged
- [x] deprecate Ops.Math.Max2
- [x] deprecate Ops.Anim.RelativeTime
- [x] rename Ops.Value.DelayedValueSimple to Ops.Value.DelayedNumberSimple
- [x] old2new string converter
- [x] Ops.TimeLine.TimeLineUI Ops.Html.PlayerControlPanel_v1
- [x] Ops.Gl.Shader.SetUniformValue  to Ops.Gl.Shader.SetUniformFloat
- [x] Ops.Gl.CubeMap.CubeMapCamera_v2 / Ops.Gl.CubeMap.CubeMapCamera to renderToCubemap ?
- [x] objectstringify shows twice, strange naming does `_v0` work actually ?
- [x] deprecate CustomTextureEffectShader
- [x] deprecate Ops.Gl.Vr

## Ops.Graphics compatible ops

- orbitcontrols
- transform
- translate
- scale
- scalexyz
- perspective
- transformview
- coordinates
- getviewmatrix
- getmodelmatrix
