### ISSUE TITLE
standalone npm install problems

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables#6632]
![Screenshot 2024-11-05 at 11 41 16](https://github.com/user-attachments/assets/a003bd2b-7911-4a25-b222-9a48172f57c6)

when putting in wrong npm name
- it opens konsole with error
- it will not return to any usable state, "working..." forever
- even closing and redoing will not work, just sais command failed
- test outside the happy path

**Comment by steam0r** [comment]
- [ ] show errors to user / log: cables-gl/cables/issues/6661
- [ ] fails if node-gyp and path has a space: cables-gl/cables/issues/6657 (see: https://github.com/nodejs/node-gyp/issues/65)
- [ ] fails when packaged and no precompiled binaries: cables-gl/cables/issues/6621
- [ ] fails when mixing import/require in packages and subpackages: cables-gl/cables_electron/issues/145
- [ ] `npm install` prunes files, so suggesting to run in terminal to install is moot: cables-gl/cables_electron/issues/145
